# Generated by Django 6.0.1 on 2026-01-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
